Repository canonical/chrony-operator, pull requests merged in 2024-07, with the labels that each got.

#8 Update location of pull request template so it's used
  .github/pull_request_template.md
Labels: Libraries: OK, trivial

#7 Change charmcraft build base to ubuntu@24.04
  .github/workflows/publish_charm.yaml
  .github/workflows/test.yaml
  charmcraft.yaml
  tests/integration/conftest.py
Labels: Libraries: OK, trivial

#4 Add `tls-certificates` integration
  .github/workflows/test.yaml
  charmcraft.yaml
  lib/charms/tls_certificates_interface/v3/tls_certificates.py
  pyproject.toml
  requirements.txt
  src/charm.py
  src/chrony.py
  src/keychain.py
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/integration/utils.py
  tests/scenario/conftest.py
  tests/scenario/test_certificates.py
  tests/unit/__init__.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_chrony.py
  tests/unit/test_keychain.py
  tests/utils.py
  tox.ini
Labels: Libraries: Out of sync, complex

#11 Open NTS-KE port when NTS certificates are configured
  src/charm.py
Labels: Libraries: Out of sync

#12 Fix charm option description field
  charmcraft.yaml
Labels: Libraries: Out of sync, trivial

#13 Update README to refer to Matrix rather than Mattermost for community chat
  README.md
Labels: Libraries: Out of sync, trivial
